apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-sample-deployment
  namespace: aspnetcore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetcore-sample
  template:
    metadata:
      labels:
        app: aspnetcore-sample
    spec:
      containers:
      - name: aspnetcore-sample-webapi
        image: phadkesharanmatrixcomsec/aspnetcore-sample:logging
        ports:
        - containerPort: 8080
