apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-sample-service
  namespace: aspnetcore
spec:
  selector:
    app: aspnetcore-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
